"""
First Bank (FBN) statement redactor.

FBN narration has dozens of structural prefixes that overlap visually with
real names (e.g. a `PLP` bank-code prefix can sit immediately next to a
surname in the very next token). A vocabulary-based keep-list is too
leak-prone, so the FBN redactor takes the safer route: blank the entire
detail column wholesale.

Parser tests still work — they assert tx count, amount math, and the row-wise
reconcile invariant against the balance column, none of which depend on
narration content.

Strategy:
1. Label-anchored header redaction: "Dear" salutation, "Account No",
   "Account Name", "Generated By", the three address lines below "Dear".
2. Body: every word inside the detail x0 range (155..310) is blanked.
3. Shape-preserve every alnum reference token (Ref... values and FBN's
   S/M-prefixed transaction IDs in the Ref. Number column), so combining
   date+amount can't be used to look up a real transaction.
"""

from __future__ import annotations

import re
from typing import Any

from .._layout import classify
from .._pymupdf import rect as _rect
from ..parsers.fbn import COL_DETAIL, COL_REF
from . import register
from ._shared import (
    DEFAULT_SWEEPS,
    apply_regex_sweeps,
    page_rows,
    redact_word,
    shape_preserve,
)
from .base import Redactor

HEADER_LABELS: dict[str, str] = {
    "Account Name:": "TEST USER",
}

ACCT_NUM_RE = re.compile(r"\b\d{10}\b")

ROW_TOL = 4.0


class FBNRedactor(Redactor):
    bank = "fbn"
    format_version = "fbn-2026-01"

    def redact_header(
        self,
        page: Any,
        pending_text: list[tuple[Any, str]],
        audit: list[str],
    ) -> None:
        """Anchor on header labels and blank everything that follows on the
        same visual row. The 'Dear' salutation and the three address lines
        beneath it use multi-line bbox geometry."""
        page_rect = page.rect

        for label, replacement in HEADER_LABELS.items():
            for hit in page.search_for(label):
                target = _rect(hit.x1 + 2, hit.y0, page_rect.x1 - 20, hit.y1 + 2)
                page.add_redact_annot(target, fill=(1, 1, 1))
                pending_text.append((target, replacement))
                audit.append(f"header[{label}] -> {replacement!r}")

        for hit in page.search_for("Dear"):
            line = _rect(hit.x1 + 2, hit.y0, page_rect.x1 - 20, hit.y1 + 2)
            page.add_redact_annot(line, fill=(1, 1, 1))
            pending_text.append((line, "Test User"))
            audit.append("header[Dear] -> 'Test User'")
            for i in range(1, 4):
                addr_line = _rect(hit.x0, hit.y1 + (i - 1) * 14, page_rect.x1 - 20, hit.y1 + i * 14)
                page.add_redact_annot(addr_line, fill=(1, 1, 1))
                if i == 1:
                    pending_text.append((addr_line, "Test Address"))
                audit.append(f"header[Address-line-{i}] -> (blank)")

        for hit in page.search_for("Generated By"):
            line = _rect(hit.x1 + 2, hit.y0, page_rect.x1 - 20, hit.y1 + 2)
            page.add_redact_annot(line, fill=(1, 1, 1))
            pending_text.append((line, "0000000000 on 01-Jan-2026 00:00:00"))
            audit.append("header[Generated By] -> redacted")

    def redact_body(
        self,
        page: Any,
        pending_text: list[tuple[Any, str]],
        audit: list[str],
    ) -> None:
        for row in page_rows(page, ROW_TOL):
            covered: set[int] = set()
            apply_regex_sweeps(page, row, DEFAULT_SWEEPS, pending_text, audit, covered)

            for idx, w in enumerate(row):
                if idx in covered:
                    continue
                in_detail = COL_DETAIL[0] <= w.x0 < COL_DETAIL[1]
                in_ref = COL_REF[0] <= w.x0 < COL_REF[1]

                if in_detail:
                    redact_word(page, w, "", pending_text)
                    covered.add(idx)
                    audit.append(f"detail: {w.text!r} -> (blank)")
                elif classify(w.text) == "alnum":
                    shape = shape_preserve(w.text)
                    redact_word(page, w, shape, pending_text)
                    covered.add(idx)
                    audit.append(f"alnum: {w.text!r} -> {shape!r}")
                elif in_ref and ACCT_NUM_RE.fullmatch(w.text):
                    redact_word(page, w, "0000000000", pending_text)
                    covered.add(idx)
                    audit.append(f"acct-num: {w.text!r} -> '0000000000'")


register(FBNRedactor())
