from pathlib import Path
from typing import Any

from bankstract._pymupdf import new_doc, open_doc
from bankstract.redactors import all_redactors, get
from bankstract.redactors._shared import shape_preserve


def test_redactor_registered() -> None:
    redactor = get("fbn")
    assert redactor.bank == "fbn"
    assert "fbn" in all_redactors()


def test_shape_preserve_pattern() -> None:
    assert shape_preserve("S99999999") == "x00000000"
    assert shape_preserve("M2000000") == "x0000000"
    assert shape_preserve("Ref000000000000000") == "xxx000000000000000"
    assert shape_preserve("1234567890") == "0000000000"
    # Underscore + punctuation preserved
    assert shape_preserve("ab_99cd9e9999") == "xx_00xx0x0000"


def _synthetic_fbn_pdf(path: Path) -> Path:
    """Minimal FBN-shape statement using fake placeholder identifiers.

    No real person, business, or address may appear here — see CLAUDE.md
    directive 3.
    """
    doc: Any = new_doc()
    page: Any = doc.new_page()

    page.insert_text((50, 50), "Dear FOO BAR", fontsize=10)
    page.insert_text((50, 70), "Account No: 1234567890", fontsize=10)
    page.insert_text((50, 90), "Account Name: FOO BAR", fontsize=10)
    page.insert_text((50, 110), "Generated By 1234567890 on 01-Jan-2026 00:00:00", fontsize=10)

    # tx row (date col x0=50, narration col ~200, balance col ~500)
    page.insert_text((50, 200), "01-Jan-2026", fontsize=10)
    page.insert_text((110, 200), "S99999", fontsize=10)
    page.insert_text((160, 200), "FIP:LIT:PLP/QUUX CORP /PLACEHOLDER", fontsize=10)

    doc.save(str(path))
    doc.close()
    return path


def test_redactor_round_trip_strips_known_pii(tmp_path: Path) -> None:
    src = _synthetic_fbn_pdf(tmp_path / "in.pdf")
    dst = tmp_path / "out.pdf"

    redactor = get("fbn")
    report = redactor.redact(src, dst)
    assert report.bank == "fbn"
    assert report.pages == 1
    assert report.redactions > 0

    out: Any = open_doc(dst)
    try:
        text: str = out[0].get_text()
    finally:
        out.close()

    for leak in ("FOO", "BAR", "QUUX", "CORP", "PLACEHOLDER", "1234567890"):
        assert leak not in text, f"{leak!r} leaked into redacted output:\n{text}"
